### ISSUE TITLE
Django Integration

### ISSUE THREAD

**Issue by radzhome** [stardothosting/treb-wordpress#1]
Hey I was looking for python code out there to use to connect to IDX MLS through TREB.  This is the closest thing I found but its specifically for word-press. Any way to integrate that (make it wordpress unspecific)? If not I can fork it and make it into a python module you can import into any python web framework like Django.  Just waiting for my treb user/pass to come in to access treb data.

**Comment by stardothosting** [comment]
making this wordpress un-specific would require modifying all the references to the wordpress calls and replacing them with a function that pulls the data and stores it in JSON or similar format. then you would wrap this tool with something else that takes that data and imports it into your CMS (whatever that may be).

the purpose of this tool is for wordpress integration, but you should be able to easily branch this and adapt it for anything.
