### ISSUE TITLE
Error Processing Request:  Invalid User Code or Password 

### ISSUE THREAD

**Issue by supreetSekhon** [stardothosting/treb-wordpress#2]
When I try to use the plugin for importing data i got this error.
Error Processing Request:  Invalid User Code or Password.
Is user code is pin or username?

Error is when request goes to http://3pv.torontomls.net/data3pv/DownLoad3PVAction.asp?user_code=*&password=*

Please help me out!!

**Comment by stardothosting** [comment]
You need to sign a broker agreement with TREB and their IT department manages and coordinates providing those usernames and passwords. Not passing those variables when attempting to pull the CSV data from TREB produces this error so it doesnt really have anything to do with the script.
